system:
    dev_mode: true
    plugins:
        -
          name: aeplugin_dev_mode
        -
          name: aeplugin_scm
dev_mode:
    keyblock_interval: 0
    microblock_interval: 0
    auto_emit_microblocks: true
